data:extend({
	{
		type = "double-setting",
		name = "lurpg-player-max-speed-bonus",
		setting_type = "runtime-per-user",
        minimum_value = 0,
		default_value = 4,
		maximum_value = 10,
	},
	{
		type = "double-setting",
		name = "lurpg-map-max-speed-bonus",
		setting_type = "runtime-global",
        minimum_value = 0,
		default_value = 4,
		maximum_value = 10,
	},
	{
		type = "double-setting",
		name = "lurpg-attr-str-mult",
		setting_type = "runtime-global",
        minimum_value = 0,
		default_value = 1,
		maximum_value = 100,
	},
	{
		type = "double-setting",
		name = "lurpg-attr-agi-mult",
		setting_type = "runtime-global",
        minimum_value = 0,
		default_value = 1,
		maximum_value = 100,
	},
	{
		type = "double-setting",
		name = "lurpg-attr-dex-mult",
		setting_type = "runtime-global",
        minimum_value = 0,
		default_value = 1,
		maximum_value = 100,
	},
	{
		type = "double-setting",
		name = "lurpg-attr-int-mult",
		setting_type = "runtime-global",
        minimum_value = 0,
		default_value = 1,
		maximum_value = 100,
	},
	{
		type = "double-setting",
		name = "lurpg-attr-str-base",
		setting_type = "runtime-global",
        minimum_value = 1,
		default_value = 1.2,
		maximum_value = 10,
	},
	{
		type = "double-setting",
		name = "lurpg-attr-agi-base",
		setting_type = "runtime-global",
        minimum_value = 1,
		default_value = 1.2,
		maximum_value = 10,
	},
	{
		type = "double-setting",
		name = "lurpg-attr-dex-base",
		setting_type = "runtime-global",
        minimum_value = 1,
		default_value = 1.2,
		maximum_value = 10,
	},
	{
		type = "double-setting",
		name = "lurpg-attr-int-base",
		setting_type = "runtime-global",
        minimum_value = 1,
		default_value = 1.2,
		maximum_value = 10,
	},
})